general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "PxPlus IBM VGA 8x16", style = "Regular" }
bold = { family = "PxPlus IBM VGA 8x16", style = "Regular" }
italic = { family = "PxPlus IBM VGA 8x16", style = "Regular" }
offset = { x = 0, y = -2 } # Adjust 'y' for line spacing
#normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
#bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
#italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 28

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 1

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 750 # Adjust as needed, in milliseconds
blink_timeout = 0 # 0 disables timeout, making blinking persistent
